// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"time"
)

type Answer struct {
	QuestionID string `json:"questionId"`
	OptionID   string `json:"optionId"`
	IsCorrect  bool   `json:"isCorrect"`
}

type AnswerResponse struct {
	Message string  `json:"message"`
	Status  int32   `json:"status"`
	Data    *Answer `json:"data,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Question struct {
	ID             string            `json:"id"`
	Title          string            `json:"title"`
	QuestionOption []*QuestionOption `json:"questionOption,omitempty"`
	CreatedAt      time.Time         `json:"createdAt"`
	UpdatedAt      time.Time         `json:"updatedAt"`
}

type QuestionInput struct {
	Title   string                 `json:"title"`
	Options []*QuestionOptionInput `json:"options"`
}

type QuestionOption struct {
	ID         string    `json:"id"`
	QuestionID string    `json:"questionId"`
	Title      string    `json:"title"`
	IsCorrect  bool      `json:"isCorrect"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type QuestionOptionInput struct {
	Title     string `json:"title"`
	IsCorrect bool   `json:"isCorrect"`
}

type QuestionResponse struct {
	Message  string      `json:"message"`
	Status   int32       `json:"status"`
	Data     *Question   `json:"data,omitempty"`
	DataList []*Question `json:"dataList,omitempty"`
}
